import { s } from 'react-native-size-matters';

export const PaddingHorizontal = s(16);
export enum ENDPOINT {
  LOGIN = '/api/spc/user/login',

  CREATE_SUPPLIER = '/api/spo/supplier/create',
  MULTI_CREATE_SUPPLIER = '/api/spo/supplier/multi-create',
  UPDATE_SUPPLIER = '/api/spo/supplier/update',
  DELETE_SUPPLIER = '/api/spo/supplier/delete',
  MULTI_DELETE_SUPPLIER = '/api/spo/supplier/multi-delete',
  GET_LIST_SUPPLIER = '/api/spo/supplier/list',
  FIND_SUPPLIER = '/api/spo/supplier/find',
  SEARCH_SUPPLIER = '/api/spo/supplier/search',

  CREATE_GROUP = '/api/spc/group/create',
  MULTI_CREATE_GROUP = '/api/spc/group/multi-create',
  UPDATE_GROUP = '/api/spc/group/update',
  DELETE_GROUP = '/api/spc/group/delete',
  MULTI_DELETE_GROUP = '/api/spc/group/multi-delete',
  GET_LIST_GROUP = '/api/spc/group/list',
  FIND_GROUP = '/api/spc/group/find',
  SEARCH_GROUP = '/api/spc/group/search',

  GET_LIST_HOTEL = '/api/spc/hotel/list',

  CREATE_ANNUAL_STATIC = '/api/spc/annual-static/create',
  MULTI_CREATE_ANNUAL_STATIC = '/api/spc/annual-static/multi-create',
  UPDATE_ANNUAL_STATIC = '/api/spc/annual-static/update',
  DELETE_ANNUAL_STATIC = '/api/spc/annual-static/delete',
  MULTI_DELETE_ANNUAL_STATIC = '/api/spc/annual-static/multi-delete',
  GET_LIST_ANNUAL_STATIC = '/api/spc/annual-static/list',
  FIND_ANNUAL_STATIC = '/api/spc/annual-static/find',
  SEARCH_ANNUAL_STATIC = '/api/spc/annual-static/search',

  CREATE_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/create',
  MULTI_CREATE_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/multi-create',
  UPDATE_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/update',
  DELETE_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/delete',
  MULTI_DELETE_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/multi-delete',
  GET_LIST_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/list',
  FIND_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/find',
  SEARCH_AVERAGE_PURCHASE = '/api/spc/avegare-purchases/search',

  CREATE_ITEM_GROUP = '/api/spc/item-group/create',
  MULTI_CREATE_ITEM_GROUP = '/api/spc/item-group/multi-create',
  UPDATE_ITEM_GROUP = '/api/spc/item-group/update',
  DELETE_ITEM_GROUP = '/api/spc/item-group/delete',
  MULTI_DELETE_ITEM_GROUP = '/api/spc/item-group/multi-delete',
  GET_LIST_ITEM_GROUP = '/api/spc/item-group/list',
  FIND_ITEM_GROUP = '/api/spc/item-group/find',
  SEARCH_ITEM_GROUP = '/api/spc/item-group/search',

  CREATE_PC_ITEM_LIST = '/api/spc/pc-item-list/create',
  MULTI_CREATE_PC_ITEM_LIST = '/api/spc/pc-item-list/multi-create',
  UPDATE_PC_ITEM_LIST = '/api/spc/pc-item-list/update',
  DELETE_PC_ITEM_LIST = '/api/spc/pc-item-list/delete',
  MULTI_DELETE_PC_ITEM_LIST = '/api/spc/pc-item-list/multi-delete',
  GET_LIST_PC_ITEM_LIST = '/api/spc/pc-item-list/list',
  FIND_PC_ITEM_LIST = '/api/spc/pc-item-list/find',
  SEARCH_PC_ITEM_LIST = '/api/spc/pc-item-list/search',

  CREATE_ITEM_PARSTOCK = '/api/spc/item-parstock/create',
  MULTI_CREATE_ITEM_PARSTOCK = '/api/spc/item-parstock/multi-create',

  CREATE_SUPPLIER_ITEM = '/api/spo/supplier-item/create',
  MULTI_CREATE_SUPPLIER_ITEM = '/api/spo/supplier-item/multi-create',
  UPDATE_SUPPLIER_ITEM = '/api/spo/supplier-item/update',
  DELETE_SUPPLIER_ITEM = '/api/spo/supplier-item/delete',
  MULTI_DELETE_SUPPLIER_ITEM = '/api/spo/supplier-item/multi-delete',
  GET_LIST_SUPPLIER_ITEM = '/api/spo/supplier-item/list',
  FIND_SUPPLIER_ITEM = '/api/spo/supplier-item/find',
  SEARCH_SUPPLIER_ITEM = '/api/spo/supplier-item/search',

  CREATE_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/create',
  MULTI_CREATE_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/multi-create',
  UPDATE_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/update',
  DELETE_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/delete',
  MULTI_DELETE_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/multi-delete',
  GET_LIST_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/list',
  FIND_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/find',
  SEARCH_SUPPLIER_ITEM_QUOTE = '/api/spo/supplier-item-quote/search',

  CREATE_SUPPLIER_GROUP = '/api/spo/supplier-group/create',
  MULTI_CREATE_SUPPLIER_GROUP = '/api/spo/supplier-group/multi-create',
  UPDATE_SUPPLIER_GROUP = '/api/spo/supplier-group/update',
  DELETE_SUPPLIER_GROUP = '/api/spo/supplier-group/delete',
  MULTI_DELETE_SUPPLIER_GROUP = '/api/spo/supplier-group/multi-delete',
  GET_LIST_SUPPLIER_GROUP = '/api/spo/supplier-group/list',
  FIND_SUPPLIER_GROUP = '/api/spo/supplier-group/find',
  SEARCH_SUPPLIER_GROUP = '/api/spo/supplier-group/search',

  CREATE_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/create',
  MULTI_CREATE_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/multi-create',
  UPDATE_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/update',
  DELETE_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/delete',
  MULTI_DELETE_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/multi-delete',
  GET_LIST_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/list',
  FIND_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/find',
  SEARCH_SUPPLIER_GROUP_ITEM = '/api/spo/supplier-group-item/search',

  CREATE_ITEM = '/api/spc/item/create',
  MULTI_CREATE_ITEM = '/api/spc/item/multi-create',
  UPDATE_ITEM = '/api/spc/item/update',
  DELETE_ITEM = '/api/spc/item/delete',
  MULTI_DELETE_ITEM = '/api/spc/item/multi-delete',
  GET_LIST_ITEM = '/api/spc/item/list',
  FIND_ITEM = '/api/spc/item/find',
  SEARCH_ITEM = '/api/spc/item/search',

  CREATE_ITEM_UNIT = '/api/spc/item-unit/create',
  MULTI_CREATE_ITEM_UNIT = '/api/spc/item-unit/multi-create',
  UPDATE_ITEM_UNIT = '/api/spc/item-unit/update',
  DELETE_ITEM_UNIT = '/api/spc/item-unit/delete',
  MULTI_DELETE_ITEM_UNIT = '/api/spc/item-unit/multi-delete',
  GET_LIST_ITEM_UNIT = '/api/spc/item-unit/list',
  FIND_ITEM_UNIT = '/api/spc/item-unit/find',
  SEARCH_ITEM_UNIT = '/api/spc/item-unit/search',

  CREATE_ITEM_TYPE = '/api/spc/item-type/create',
  MULTI_CREATE_ITEM_TYPE = '/api/spc/item-type/multi-create',
  UPDATE_ITEM_TYPE = '/api/spc/item-type/update',
  DELETE_ITEM_TYPE = '/api/spc/item-type/delete',
  MULTI_DELETE_ITEM_TYPE = '/api/spc/item-type/multi-delete',
  GET_LIST_ITEM_TYPE = '/api/spc/item-type/list',
  FIND_ITEM_TYPE = '/api/spc/item-type/find',
  SEARCH_ITEM_TYPE = '/api/spc/item-type/search',

  CREATE_PR = '/api/spo/pr/create',
  MULTI_CREATE_PR = '/api/spo/pr/multi-create',
  UPDATE_PR = '/api/spo/pr/update',
  DELETE_PR = '/api/spo/pr/delete',
  MULTI_DELETE_PR = '/api/spo/pr/multi-delete',
  GET_LIST_PR = '/api/spo/pr/list',
  FIND_PR = '/api/spo/pr/find',
  SEARCH_PR = '/api/spo/pr/search',

  APPROVE_PR = '/api/spo/pr/approve',
  REJECT_PR = '/api/spo/pr/reject',

  CREATE_PR_ITEM = '/api/spo/pr-item/create',
  MULTI_CREATE_PR_ITEM = '/api/spo/pr-item/multi-create',
  UPDATE_PR_ITEM = '/api/spo/pr-item/update',
  DELETE_PR_ITEM = '/api/spo/pr-item/delete',
  MULTI_DELETE_PR_ITEM = '/api/spo/pr-item/multi-delete',
  GET_LIST_PR_ITEM = '/api/spo/pr-item/list',
  FIND_PR_ITEM = '/api/spo/pr-item/find',
  SEARCH_PR_ITEM = '/api/spo/pr-item/search',

  IMPORT_PR_ITEM_EXCEL = '/api/spo/pr-item/import-pr-item-excel',

  CREATE_QUOTE = '/api/spo/quote/create',
  MULTI_CREATE_QUOTE = '/api/spo/quote/multi-create',
  UPDATE_QUOTE = '/api/spo/quote/update',
  DELETE_QUOTE = '/api/spo/quote/delete',
  MULTI_DELETE_QUOTE = '/api/spo/quote/multi-delete',
  GET_LIST_QUOTE = '/api/spo/quote/list',
  FIND_QUOTE = '/api/spo/quote/find',
  SEARCH_QUOTE = '/api/spo/quote/search',

  APPROVE_QUOTE = '/api/spo/quote/approve',
  REJECT_QUOTE = '/api/spo/quote/reject',

  CREATE_QUOTE_ITEM = '/api/spo/quote-item/create',
  MULTI_CREATE_QUOTE_ITEM = '/api/spo/quote-item/multi-create',
  UPDATE_QUOTE_ITEM = '/api/spo/quote-item/update',
  DELETE_QUOTE_ITEM = '/api/spo/quote-item/delete',
  MULTI_DELETE_QUOTE_ITEM = '/api/spo/quote-item/multi-delete',
  GET_LIST_QUOTE_ITEM = '/api/spo/quote-item/list',
  FIND_QUOTE_ITEM = '/api/spo/quote-item/find',
  SEARCH_QUOTE_ITEM = '/api/spo/quote-item/search',

  IMPORT_QUOTE_ITEM_EXCEL = '/api/spo/quote-item/import-quote-item-excel',
}
